from character_new import *
from enemy_new import *

MENU_OPTION = "Choose the option you want to perform:\n 1: Choose character\n 2: Remove character:\n 3: Exit"
CHOICE = "Your choice: "
WRONG = "Your choice is incorrect"
FIGHT = "Press ENTER to fight"
DAMAGE_CAUSED = f"Damage caused by: "
HEALTH_POINTS = "HP"
DEAD = "is dead!"
CURRENT_HEALTH = "Current health of "
LEVEL_UP = "has leveled up!"
CHAR_AMOU = "How many characters do you want to add? (3 max): "
CHAR_AMOUN_ERR = "You can add up to 3 characters, 1 minimum!"
TYPES_CHAR = "Enter the type of character you want: \n 1:Orc: You'll get 2 extra points in strength\n 2:Elf: You'll get 2 extra points in agility\n 3:Human: You'll get 2 extra points in constitution"
CHOICE_ERR = "Your choice is not in the options!"
CHAR_NAME = "Please, enter the character's name: "
CHAR_AGE = "Please, enter character's age:"
SUM_ATTRIBS = "The sum of strength, agility and constitution must be 15, and no attribute can be equal to 0"
CHAR_STR = "Enter character's strength: "
YOU_HAVE = "You have"
POINTS_LEFT = "points left."
CHAR_AGI = "Enter character's agility: "
CHAR_CONS = "Enter character's constitution: "
SUM_ERR = "THE SUM OF THE STATS MUST BE 15, PLEASE ENTER THE VALUES AGAIN"
